### PR TITLE
package for npm distribution

### PR DESCRIPTION
**Pull request by visnup**
so it can be used via [browserify](http://blog.npmjs.org/post/114584444410/using-angulars-new-improved-browserify-support) or webpack.

I don't know if I did this correctly though so that it can still run ok for bower...

### CODE REVIEW

**Comment by Hypercubed** [comment]
Adding the dependency into package.json is right on... but the `require('marked')` line wont work.  If anything it should be something like `require  ? require('marked') : $window.marked || marked`  But I thought this was not needed.  Can you specify the requirement elsewhere? I really need learn how to use browserify.

**Comment by Hypercubed** [comment]
I'm trying this...

```
      var m =  (function() {

        if (typeof module !== 'undefined' && typeof exports === 'object') {
          return require('marked');
        } else {
          return $window.marked || marked;
        }

      })();
```

Please let me know how it works.

**Comment by visnup** [comment]
ooh awesome! sorry I didn't respond earlier. I'll try this out. thanks again!

**Comment by visnup** [comment]
verified this works for me. thanks!

**Pull request merged**
