### PR TITLE
created meteor package files

### PR DESCRIPTION
**Pull request by oshai**
in order to complete package deployment to atmosphere (meteor's package manager) you have to run:
meteor publish --create
from this directory after installing meteor.

### CODE REVIEW

**Comment by Hypercubed** [comment]
I'm sorry, I don't know anuthing about meteor.  What is the .version file and why does it point to your repo?

**Comment by oshai** [comment]
My name was there by mistake, I fixed it. the version file is a hint for the versions of the dependencies packages it is going to use. from meteor documentation:

`Meteor promises repeatable builds for both packages and applications. This means that, if you built your package on a machine, then checked the code into a repository and checked it out elsewhere, you should get the same result. In your package directory, you will find an automatically generated .versions file. This file specifies the versions of all packages used to build your package and is part of the source. Check it into version control to ensure repeatable builds across machines.`

**Comment by Hypercubed** [comment]
hmmm.. I was going to merge this but do I really need to maintain another set of version numbers?

**Comment by oshai** [comment]
there are more details here: http://angular-meteor.com/tutorial/step_19
I think there is a way to integrate it in the build process, but never
tried it.

**Comment by Hypercubed** [comment]
@oshai I don't know anything about meteor so I am hesitant to merge this... also, I recently refactored the files in the project.  If you still need this please reopen.  Thanks.

**Comment by oshai** [comment]
Thanks, currently I don't need it.

**Pull request closed without merging**
