### PR TITLE
Added ability to convert text to markdown after 

### PR DESCRIPTION
**Pull request by vytautas-pranskunas-**
# Added ability to convert text to markdown after 
# Reduced watchers count
# Updated jasmine version

### CODE REVIEW

**Comment by Hypercubed** [comment]
Hello @vytautas-pranskunas- it may take me some time to look at this.  I tried this before but it failed.  I'll have to look at your implementation closely.

**Comment by Hypercubed** [comment]
It might be easier if you break this into separate PRs.  For the RequireJs patch I plan to write this in CommonJS then apply browserify to convert to UMD.

**Comment by vytautas-pranskunas-** [comment]
Sure, anyway I found one bug and have to fix it.

**Comment by vytautas-pranskunas-** [comment]
I have closed this pull request since it had a bug in compilation code. However part with requireJs and reducing watchers count are correct. I would not fix that bug since that approach is not correct at all. I have redesigned this directive from scratch (using TypeScript) and will put to github if there is a need.

**Comment by Hypercubed** [comment]
I'm interested to see what you can do differently with typescript.  So the result is two featire requests:

1) Support RequireJS  -- Solved by compiling to UMD
2) compileOnce -- Can we do the same with a "::" binding?

**Comment by vytautas-pranskunas-** [comment]
Difference is not typescript. Typescript is just a super-set of javascript. I mentioned it only because code is more structural now. 
Requsts were:
1) Support of requieJs
2) compileOnce - (Can we do the same with a "::" binding?: and yes and no i mean we can do it with :: but interpolation does not work 100% correct because of some kind of racing condition with my peace of code in pull request) but without it you can improve your watchers count with scope.destroy()
3) Thing I was looking for is to have <marked>**some markdown** {{ someVariable}} *someMakrdown*<marked> as well as <marked src="someFIle.html"></marked> where file content is: **some markdown** {{ someVariable}} *someMakrdown*

As I mentioned I will add implementation to my repository later this weekend

**Pull request closed without merging**
