### PR TITLE
Compile option

### LINKED ISSUE #51: Possible to hook into markdown content with angular events (ng-click, etc...)
For instance, I want to make all images appear smaller in the rendered markdown, and on click, show the image version in a lightbox.  Is that possible?  The markdown content has `` tags that I can parse and render in the controller using the `marked` service, but my attempts to add `ng-click` events have been less than fruitful.

### PR DESCRIPTION
**Pull request by Toilal**
It's there, should fix #51 and #43.

I've added unit tests, i'm quite confident but I still need to test in real world though (by integrating this branch into my own project, results comming soon).

### CODE REVIEW

**Comment by Toilal** [comment]
I understand the build process now, but unit tests are now failing for some reason. Any idea ?

**Comment by Toilal** [comment]
although, i've linked this branch to my project, and the compile option works has expected.

**Comment by Toilal** [comment]
Ho I think it's because jarmine version defined in package.json is old, and it breaks because of commit 96f2c8338a96bc8037cfc3a8d73ac2001fa11354

**Comment by Toilal** [comment]
Ok, I've upgrade karma dependencies to latest version, tests are OK now.

**Comment by Toilal** [comment]
There's still some work to do according to #43, [this test](https://github.com/Hypercubed/angular-marked/blob/master/test/angular-marked.js#L136) is still failing.

I'll try to make it pass tomorrow.

**Comment by Toilal** [comment]
I think it's ready to merge. I've  updated the ignored test and it's now OK.

Maybe `compile="true"` should be default now ?

**Comment by ggoforth** [comment]
Sweet, thanks for the PR @Toilal! Looking forward to this!

**Comment by Hypercubed** [comment]
Looks good!  I modified a couple of things and fixed a bug you introduced here: https://github.com/Hypercubed/angular-marked/pull/56/files#diff-b0b7fb5b84791579a4984ba237052f90L74

But mostly looks like it is working!  I published this as v1.1.0.

Thank you.

**Comment by ggoforth** [comment]
Thanks @Hypercubed!

**Pull request merged**
